const {test}=require('node:test');const assert=require('node:assert/strict');const {spawnSync}=require('node:child_process');const path=require('node:path');const cli=path.resolve(__dirname,'../../tools/clis/close.js')
function run(args,network=true){const script=`global.fetch=async(url,options)=>{if(!${network})throw new Error('Unexpected network');return{status:200,text:async()=>JSON.stringify({url,method:options.method,has_more:false,data:[]})}};process.argv=['node',${JSON.stringify(cli)},...${JSON.stringify(args)}];require(${JSON.stringify(cli)})`;return spawnSync(process.execPath,['-e',script],{encoding:'utf8',timeout:5000,env:{CLOSE_API_KEY:'fixture-key',PATH:process.env.PATH}})}
function out(r){assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout)}
const resources=['leads','contacts','opportunities','activities','tasks']
test('page offsets follow the selected page size across CRM collections',()=>{for(const resource of resources){const u=new URL(out(run([resource,'list','--page','2','--limit','25'])).url);assert.equal(u.searchParams.get('_skip'),'25',resource);assert.equal(u.searchParams.get('_limit'),'25')}})
test('explicit offsets and zero retain filters and provider responses',()=>{const r=out(run(['contacts','list','--skip','0','--limit','100','--lead-id','lead/+id']));const u=new URL(r.url);assert.equal(u.searchParams.get('_skip'),'0');assert.equal(u.searchParams.get('lead_id'),'lead/+id');assert.deepEqual(r.data,[]);assert.equal(r.has_more,false)})
test('omission and legacy page selection retain established semantics',()=>{assert.equal(new URL(out(run(['leads','list'])).url).search,'');const u=new URL(out(run(['leads','list','--page','2'])).url);assert.equal(u.searchParams.get('_skip'),'100');assert.equal(u.searchParams.get('_limit'),'100')})
test('malformed and ambiguous pagination fails before fetch',()=>{for(const flags of [['--page','0'],['--page','2junk'],['--page'],['--skip','-1'],['--limit','101'],['--limit','1.5'],['--page','2','--skip','25']]){const r=run(['contacts','list',...flags],false);assert.equal(r.status,1);assert.doesNotMatch(r.stderr,/Unexpected network/)}})
test('dry run is paginated and credential-redacted',()=>{const r=out(run(['tasks','list','--page','3','--limit','10','--dry-run'],false));assert.equal(new URL(r.url).searchParams.get('_skip'),'20');assert.equal(JSON.stringify(r).includes('fixture-key'),false)})
