const { test } = require('node:test')
const assert = require('node:assert/strict')
const { spawnSync } = require('node:child_process')
const path = require('node:path')
const cli=path.resolve(__dirname,'../../tools/clis/trustpilot.js')
function run(args,oracle="throw new Error('unexpected fetch')") {
  const code=`global.fetch=async(url,options)=>{const assert=require('node:assert/strict');if(${JSON.stringify(args.includes('--dry-run'))})throw new Error('unexpected preview fetch');const u=new URL(url);if(u.pathname.includes('/oauth/')){assert.equal(u.host,'api.trustpilot.com');assert.equal(options.body,'grant_type=client_credentials');return new Response(JSON.stringify({access_token:'fixture-token'}));}const body=options.body?JSON.parse(options.body):undefined;${oracle};return new Response(JSON.stringify({accepted:true}));};process.argv=['node',${JSON.stringify(cli)},...${JSON.stringify(args)}];require(${JSON.stringify(cli)});`
  const r=spawnSync(process.execPath,['-e',code],{encoding:'utf8',timeout:10000,env:{...process.env,TRUSTPILOT_API_KEY:'fixture-key',TRUSTPILOT_API_SECRET:'fixture-secret',TRUSTPILOT_BUSINESS_UNIT_ID:'business1'}});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout)
}
const emailArgs=['invitations','create','--email','jane@example.com','--name','Jane','--template','t1','--sender-email','sender@example.com','--sender-name','Team','--reply-to','reply@example.com','--redirect-uri','https://example.com/thanks','--business-user-id','user1']
test('email invitations use the invitation host and nested service review payload',()=>assert.equal(run(emailArgs,"assert.equal(u.href,'https://invitations-api.trustpilot.com/v1/private/business-units/business1/email-invitations');assert.equal(options.method,'POST');assert.equal(options.headers.Authorization,'Bearer fixture-token');assert.equal(options.headers['x-business-user-id'],'user1');assert.deepEqual(body,{consumerEmail:'jane@example.com',consumerName:'Jane',referenceNumber:'',senderEmail:'sender@example.com',senderName:'Team',replyTo:'reply@example.com',type:'email',serviceReviewInvitation:{templateId:'t1',redirectUri:'https://example.com/thanks'}});").accepted,true))
test('invitation link retains its distinct payload on the invitation host',()=>assert.equal(run(['invitations','link','--email','jane@example.com','--name','Jane'],"assert.equal(u.host,'invitations-api.trustpilot.com');assert.equal(u.pathname,'/v1/private/business-units/business1/invitation-links');assert.deepEqual(body,{email:'jane@example.com',name:'Jane',referenceId:'',redirectUri:'https://trustpilot.com'});").accepted,true))
test('invitation templates use the invitation host',()=>assert.equal(run(['invitations','templates'],"assert.equal(u.href,'https://invitations-api.trustpilot.com/v1/private/business-units/business1/templates');assert.equal(options.method,'GET');").accepted,true))
test('ordinary review reads still use the core API and key authentication',()=>assert.equal(run(['reviews','get','--id','r1'],"assert.equal(u.href,'https://api.trustpilot.com/v1/reviews/r1');assert.equal(options.headers.apikey,'fixture-key');assert.equal(options.headers.Authorization,undefined);").accepted,true))
test('invitation preview retains nested fields and sends neither OAuth nor invitations',()=>{const p=run([...emailArgs,'--dry-run']);assert.equal(new URL(p.url).host,'invitations-api.trustpilot.com');assert.equal(p.body.serviceReviewInvitation.templateId,'t1');assert.equal(p.headers.Authorization,'***');assert.equal(p.headers['x-business-user-id'],'user1')})
